name: Release

on:
  push:
    branches: [main]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        uses: hmarr/debug-action@v2
      - name: Checkout
        uses: actions/checkout@master
      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 0.0.1
      - name: Get next minor version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - run: echo "previous tag" ${{steps.previoustag.outputs.tag }}
      # - run: echo "PREV_TAG=$({{ steps.previoustag.outputs.tag }})" >> $GITHUB_ENV
      # - run: echo "NEXT_TAG=$({{ steps.semvers.outputs.v_patch }})" >> $GITHUB_ENV
      - run: echo ${{ steps.previoustag.outputs.tag }}
      - run: echo ${{ steps.semvers.outputs.v_patch }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          event-type: print
          client-payload: '{"previous_tag": "${{ steps.previoustag.outputs.tag }}", "next_tag": "${{ steps.semvers.outputs.v_patch }}"}'
