name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    if: ${{ github.event.head_commit.author.name != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: debug
        uses: hmarr/debug-action@v2
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 0.0.1
      - name: Get next minor version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - run: echo "previous tag" ${{steps.previoustag.outputs.tag }}
      - run: echo "next tag    " ${{ steps.semvers.outputs.v_patch }}
      - name: Set git info
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - run: npm version ${{steps.semvers.outputs.v_patch }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tags: true
          branch: ${{ github.ref }}
